name: fwdpy_docs

channels:
    - conda-forge
    - defaults
    - r
    - bioconda

dependencies:
    - python==3.5
    - sphinx_rtd_theme
    - gsl
    - doxygen
    - pip:
        - numpy
        - breathe

