name: fwdpy_docs

channels:
    - defaults
    - conda-forge
    - bioconda

dependencies:
    - python==3.5
    - sphinx_rtd_theme==0.1.9
    - pybind11==2.2.1
    - gsl
    - nbsphinx
    - msprime
    - gcc
    - numpy
    - pandas
    - matplotlib
    - ipython
    - pip:
        - cppimport
