name: fwdpy_docs

channels:
    - conda-forge
    - defaults
    - bioconda

dependencies:
    - python==3.5
    - sphinx_rtd_theme==0.1.9
    - gsl
    - nbsphinx
    - msprime
    - pip:
        - numpy
        - matplotlib
        - ipython
        - cppimport
